# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"train_dataset_fp": "mlops.ipynb",
         "column_names": "mlops.ipynb",
         "feature_names": "mlops.ipynb",
         "label_name": "mlops.ipynb",
         "class_names": "mlops.ipynb",
         "batch_size": "mlops.ipynb",
         "train_dataset": "mlops.ipynb",
         "pack_features_vector": "mlops.ipynb",
         "model": "mlops.ipynb",
         "predictions": "mlops.ipynb",
         "loss_object": "mlops.ipynb",
         "loss": "mlops.ipynb",
         "l": "mlops.ipynb",
         "grad": "mlops.ipynb",
         "optimizer": "mlops.ipynb",
         "train_loss_results": "mlops.ipynb",
         "train_accuracy_results": "mlops.ipynb",
         "num_epochs": "mlops.ipynb",
         "test_fp": "mlops.ipynb",
         "test_dataset": "mlops.ipynb",
         "test_accuracy": "mlops.ipynb",
         "predict_dataset": "mlops.ipynb"}

modules = ["train.py",
           "test.py",
           "smoke.py"]

doc_url = "https://fastai.github.io/nbdev_template/"

git_url = "https://github.com/fastai/nbdev_template/tree/master/"

def custom_doc_links(name): return None
