# AUTOGENERATED! DO NOT EDIT! File to edit: 00_create_train.ipynb (unless otherwise specified).

__all__ = ['train_dataset_fp', 'column_names', 'feature_names', 'label_name', 'class_names', 'batch_size',
           'train_dataset', 'pack_features_vector', 'train_dataset', 'model', 'predictions', 'loss_object', 'loss', 'l',
           'grad', 'optimizer', 'train_loss_results', 'train_accuracy_results', 'num_epochs']

# Comes from mlops.ipynb, cell
import os
import matplotlib.pyplot as plt
import tensorflow as tf
print("TensorFlow version: {}".format(tf.__version__))
print("Eager execution: {}".format(tf.executing_eagerly()))

# Comes from mlops.ipynb, cell
train_dataset_fp = "iris_training.csv"

# Comes from mlops.ipynb, cell
# column order in CSV file
column_names = ['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'species']

feature_names = column_names[:-1]
label_name = column_names[-1]

# Comes from mlops.ipynb, cell
class_names = ['Iris setosa', 'Iris versicolor', 'Iris virginica']

# Comes from mlops.ipynb, cell
batch_size = 32

train_dataset = tf.data.experimental.make_csv_dataset(
    train_dataset_fp,
    batch_size,
    column_names=column_names,
    label_name=label_name,
    num_epochs=1)

# Comes from mlops.ipynb, cell
features, labels = next(iter(train_dataset))

# Comes from mlops.ipynb, cell
def pack_features_vector(features, labels):
  """Pack the features into a single array."""
  features = tf.stack(list(features.values()), axis=1)
  return features, labels

# Comes from mlops.ipynb, cell
train_dataset = train_dataset.map(pack_features_vector)

# Comes from mlops.ipynb, cell
features, labels = next(iter(train_dataset))

# Comes from mlops.ipynb, cell
model = tf.keras.Sequential([
  tf.keras.layers.Dense(10, activation=tf.nn.relu, input_shape=(4,)),  # input shape required
  tf.keras.layers.Dense(10, activation=tf.nn.relu),
  tf.keras.layers.Dense(3)
])

# Comes from mlops.ipynb, cell
predictions = model(features)

# Comes from mlops.ipynb, cell
loss_object = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

# Comes from mlops.ipynb, cell
def loss(model, x, y, training):
  # training=training is needed only if there are layers with different
  # behavior during training versus inference (e.g. Dropout).
  y_ = model(x, training=training)

  return loss_object(y_true=y, y_pred=y_)


l = loss(model, features, labels, training=False)

# Comes from mlops.ipynb, cell
def grad(model, inputs, targets):
  with tf.GradientTape() as tape:
    loss_value = loss(model, inputs, targets, training=True)
  return loss_value, tape.gradient(loss_value, model.trainable_variables)

# Comes from mlops.ipynb, cell
optimizer = tf.keras.optimizers.SGD(learning_rate=0.01)

# Comes from mlops.ipynb, cell
loss_value, grads = grad(model, features, labels)

# Comes from mlops.ipynb, cell
optimizer.apply_gradients(zip(grads, model.trainable_variables))

# Comes from mlops.ipynb, cell
## Note: Rerunning this cell uses the same model variables

# Keep results for plotting
train_loss_results = []
train_accuracy_results = []

num_epochs = 201

for epoch in range(num_epochs):
  epoch_loss_avg = tf.keras.metrics.Mean()
  epoch_accuracy = tf.keras.metrics.SparseCategoricalAccuracy()

  # Training loop - using batches of 32
  for x, y in train_dataset:
    # Optimize the model
    loss_value, grads = grad(model, x, y)
    optimizer.apply_gradients(zip(grads, model.trainable_variables))

    # Track progress
    epoch_loss_avg.update_state(loss_value)  # Add current batch loss
    # Compare predicted label to actual label
    # training=True is needed only if there are layers with different
    # behavior during training versus inference (e.g. Dropout).
    epoch_accuracy.update_state(y, model(x, training=True))

  # End epoch
  train_loss_results.append(epoch_loss_avg.result())
  train_accuracy_results.append(epoch_accuracy.result())

  if epoch % 50 == 0:
    print("Epoch {:03d}: Loss: {:.3f}, Accuracy: {:.3%}".format(epoch,
                                                                epoch_loss_avg.result(),
                                                                epoch_accuracy.result()))